package org.customer.model;

public enum Province {
    DOLNOSLASKIE,
    KUJAWSKO_POMORSKIE,
    LUBELSKIE,
    LUBUSKIE,
    LODZKIE,
    MALOPOLSKIE,
    MAZOWIECKIE,
    OPOLSKIE,
    PODKARPACKIE,
    PODLASKIE,
    POMORSKIE,
    SLASKIE,
    SWIETOKRZYSKIE,
    WARMIŃSKO_MAZURSKIE,
    WIELKOPOLSKIE,
    ZACHODNIOPOMORSKIE
}